### ISSUE TITLE
Polling_frequency unused

### ISSUE THREAD

**Issue by jesperplantenervisma** [aws-samples/aws-mainframe-modernization-controlm-integration#3]
When deploying the M2Job definition in Control-M, there's a warning saying that the variable `polling_frequency` is unsued by the job type.
This indicates that even though the job type does take an input `polling_frequency`, it's actually not in use by the job type.

**Comment by djjaegle** [comment]
Actually this seems to be a bug with how the Control-M App Integrator works. The `polling_frequency` is used within the Execution - Start Batch Job step of the configuration. It is specifically used in the Verify Operation Complete sub-step to pull M2 for the status of the job execution. Not sure why the App Integrator tooling throws that error.

**Comment by jesperplantenervisma** [comment]
@djjaegle Thanks for looking into it. It seems like you are right, so I will close the issue here.
